# Generated by Django 4.2.20 on 2025-05-06 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_G2S', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 4, 35, 11, 756561, tzinfo=datetime.timezone.utc), help_text="Elle s'auto saisie"),
        ),
        migrations.RemoveField(
            model_name='examen',
            name='classe',
        ),
        migrations.AddField(
            model_name='examen',
            name='classe',
            field=models.ManyToManyField(to='APP_G2S.classe', verbose_name='Classe'),
        ),
    ]
