# Generated by Django 4.2.20 on 2025-05-06 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_G2S', '0002_alter_eleve_code_expiry_remove_examen_classe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examen',
            name='unique_examen_date_classe',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 4, 37, 3, 939132, tzinfo=datetime.timezone.utc), help_text="Elle s'auto saisie"),
        ),
    ]
