# Generated by Django 4.2.20 on 2025-05-06 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_G2S', '0003_remove_examen_unique_examen_date_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 4, 59, 6, 674185, tzinfo=datetime.timezone.utc), help_text="Elle s'auto saisie"),
        ),
        migrations.RemoveField(
            model_name='periode',
            name='classe',
        ),
        migrations.AddField(
            model_name='periode',
            name='classe',
            field=models.ManyToManyField(to='APP_G2S.classe', verbose_name='classe_in_periode'),
        ),
    ]
