# Generated by Django 4.2.20 on 2025-05-06 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_G2S', '0004_alter_eleve_code_expiry_remove_periode_classe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periode',
            name='unique_annee_classe',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 19, 16, 55, 686631, tzinfo=datetime.timezone.utc), help_text="Elle s'auto saisie"),
        ),
        migrations.AlterField(
            model_name='periode',
            name='classe',
            field=models.ManyToManyField(to='APP_G2S.classe', verbose_name='Classe'),
        ),
    ]
