# Generated by Django 4.2.20 on 2025-05-07 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_G2S', '0005_remove_periode_unique_annee_classe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note_par_matiere',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 14, 21, 47, 466123, tzinfo=datetime.timezone.utc), help_text="Elle s'auto saisie"),
        ),
    ]
